manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zzeneg
      url-base: https://github.com/zzeneg
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-split-peripheral-output-relay
      remote: oleksandrmaslov
      revision: peripheral
  self:
    path: config
